apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opwerf.fullname" . }}-api
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "opwerf.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opwerf.fullname" . }}-worker
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{- include "opwerf.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opwerf.fullname" . }}-credential-proxy
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: credential-proxy
      {{- include "opwerf.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opwerf.fullname" . }}-dashboard
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: dashboard
      {{- include "opwerf.selectorLabels" . | nindent 6 }}
