apiVersion: v1
kind: Service
metadata:
  name: {{ include "opwerf.fullname" . }}-api
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opwerf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opwerf.fullname" . }}-dashboard
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "opwerf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opwerf.fullname" . }}-credential-proxy
  labels:
    {{- include "opwerf.labels" . | nindent 4 }}
    app.kubernetes.io/component: credential-proxy
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opwerf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: credential-proxy
