apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-sdlc-orchestrator.fullname" . }}-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: api
---
{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-sdlc-orchestrator.fullname" . }}-dashboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/component: dashboard
{{- end }}
